# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('name', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('pretty_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('icon_url', models.CharField(max_length=256)),
                ('result_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('species_custom', models.CharField(max_length=256, null=True)),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Species')),
            ],
        ),
        migrations.AddField(
            model_name='response',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='survey.User'),
        ),
        migrations.AddField(
            model_name='response',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.Species'),
        ),
        migrations.AddField(
            model_name='response',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='survey.User'),
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=set([('source', 'target')]),
        ),
    ]
